version: '2'
services:
    application:
        container_name: outdated-browser-bundle_app
        build: .
        expose:
            - "9000"
        volumes:
            - .:/var/www/symfony
        links:
            - mysql:mysql
    mysql:
        container_name: outdated-browser-bundle_mysql
        image: chaplean/mysql
        volumes:
            - ./.db:/var/lib/mysql:rw
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: app_user
            MYSQL_PASSWORD: app_password
            MYSQL_DATABASE: test_database
networks: {}
volumes: {}
