chaplean_outdated_browser_index:
    path: /
    defaults: { _controller: ChapleanOutdatedBrowserBundle:Default:index }

chaplean_outdated_browser_bundle:
    resource: "@ChapleanOutdatedBrowserBundle/Resources/config/routing.yml"
    prefix:   /